### ISSUE TITLE
Add permission for another group on a page

### ISSUE THREAD

**Issue by gdumanoir** [lordlamer/knowledgeroot#34]
Hi,

When I try to add right for another group for a page, and save, the change is not applied.
Ie if I go into the permission tab again, the new right for the group is not there anymore.

Thanks

Regards

**Comment by gdumanoir** [comment]
Hi,
I found a workaround : I was doing my tests in french language.
When I switched to english, I discovered that is is working...

Weird, why the language used for the interface can change the behavior of Knowledge Root ?

Thanks

Regards

**Comment by lordlamer** [comment]
Hi,

which knowledgeroot version are you using?
Could you add a screenshot from the permission tab/page?

Frank

**Comment by gdumanoir** [comment]
Hi,

This is version 1.0.3.

To take some screenshots, I tried to reproduce the problem by changing back my langage to French.
I am unable to reproduce it...

Sorry about that...

Guillame

**Comment by lordlamer** [comment]
no problem ;)
